Remove dialog_ng module (not available in Kamailio 6.0)
Error: could not find module <dialog_ng>
Cause: dialog_ng module doesn't exist in Kamailio 6.0.x
Fix: Removed loadmodule "dialog_ng.so" - dialog.so provides all needed functionality